/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qrcode;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.client.j2se.MatrixToImageConfig;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Thomas
 */
public class Generator extends javax.swing.JFrame {

    /**
     * Creates new form Generator
     */
    public Generator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        layeredPane = new javax.swing.JLayeredPane();
        generatePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        txtGenerateQR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        readPanel = new javax.swing.JPanel();
        btnReadQR = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReadContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("READ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 100, 36));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GENERATE");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 110, 36));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QR CODE GENERATOR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("(QUICK RESPONSE CODE)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 240, -1));

        txtName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("jLabel1");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 6, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 838, 83));

        layeredPane.setLayout(new java.awt.CardLayout());

        generatePanel.setBackground(new java.awt.Color(5, 0, 0));
        generatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtContent.setLineWrap(true);
        txtContent.setRows(5);
        txtContent.setMargin(new java.awt.Insets(50, 50, 50, 50));
        jScrollPane1.setViewportView(txtContent);

        generatePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 55, 480, 230));

        txtGenerateQR.setBackground(new java.awt.Color(5, 0, 0));
        txtGenerateQR.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtGenerateQR.setForeground(new java.awt.Color(255, 255, 255));
        txtGenerateQR.setText("GENERATE");
        txtGenerateQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenerateQRActionPerformed(evt);
            }
        });
        generatePanel.add(txtGenerateQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 130, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("your code");
        generatePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter your text to generate");
        generatePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, -1));

        layeredPane.add(generatePanel, "card2");

        btnReadQR.setText("jButton3");
        btnReadQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadQRActionPerformed(evt);
            }
        });

        txtReadContent.setColumns(20);
        txtReadContent.setRows(5);
        jScrollPane3.setViewportView(txtReadContent);

        javax.swing.GroupLayout readPanelLayout = new javax.swing.GroupLayout(readPanel);
        readPanel.setLayout(readPanelLayout);
        readPanelLayout.setHorizontalGroup(
            readPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPanelLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(readPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readPanelLayout.createSequentialGroup()
                        .addComponent(btnReadQR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        readPanelLayout.setVerticalGroup(
            readPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnReadQR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        layeredPane.add(readPanel, "card3");

        getContentPane().add(layeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 838, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenerateQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenerateQRActionPerformed
        // TODO add your handling code here:
        
        Map<EncodeHintType, ErrorCorrectionLevel> hints = new HashMap<>();
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
        
        QRCodeWriter writer = new QRCodeWriter();
        BitMatrix bitmatrix = null;
        //ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
//            Create a QR code with the URL as content and size of 250*250.
            bitmatrix = writer.encode(txtContent.getText(), BarcodeFormat.QR_CODE, 250, 250, hints);
//            txtContent.setText(writer.toString());

//            bitmatrix = writer.encode("I am Obinna Emmanuel, a web developer and graphics designer."
//                    + " For more enquiries, WhatsApp or call me on +2348105581430.", BarcodeFormat.QR_CODE, 250, 250);
            MatrixToImageConfig config = new MatrixToImageConfig(MatrixToImageConfig.BLACK, MatrixToImageConfig.WHITE);

            //Loads the QR Image
            BufferedImage qrimage = MatrixToImageWriter.toBufferedImage(bitmatrix, config);

            //Loads Logo Image
//            File file = new File("C:\\Users\\Thomas\\Pictures\\logoiread.png");
//            BufferedImage logoimage = ImageIO.read(file);
            //Calculates the deltaHeight and Width between the QR code and logo.
//            int deltaHeight = qrimage.getHeight() - logoimage.getHeight();
//            int deltaWidth = qrimage.getHeight() - logoimage.getWidth();
            //Initializes combined image
            BufferedImage combine = new BufferedImage(qrimage.getHeight(), qrimage.getWidth(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = (Graphics2D) combine.getGraphics();

            //Writes QR Code to new image at position at 0/0
            g.drawImage(qrimage, 0, 0, null);
            g.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER));

//            g.drawImage(logoimage, (int) Math.round(deltaHeight / 4), (int) Math.round(deltaWidth / 2), null);
            //Writes combined image as png to outputStream
            JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(this);
            File file = chooser.getSelectedFile();
            ImageIO.write(combine, "png", file);
            System.out.println("Done");
            JOptionPane.showMessageDialog(this, "Generated");
        } catch (WriterException | IOException e) {
            System.out.println(e);
            
        }
        
    }//GEN-LAST:event_txtGenerateQRActionPerformed

    private void btnReadQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadQRActionPerformed
        // TODO add your handling code here:
        
        try {
            
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            
            if (file == null) {
                throw new Exception("Invalid file selected,,,,,,,,,,");
            }

//            File file = new File("C:\\Users\\Thomas\\Pictures\\Obitec.png");
            Result out = new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(ImageIO.read(file)))));

//            JOptionPane.showMessageDialog(null, out.getText());
            JOptionPane.showMessageDialog(null, out.getText(), "QR code content", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(file.getAbsolutePath()));
            txtReadContent.setText(out.getText());
            
            System.out.println(out.getText());
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnReadQRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        changePanel(generatePanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        changePanel(readPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generator().setVisible(true);
            }
        });
    }
    
    public void changePanel(JPanel panel) {
        
        layeredPane.removeAll();
        layeredPane.add(panel);
        layeredPane.repaint();
        layeredPane.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadQR;
    private javax.swing.JPanel generatePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JPanel readPanel;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JButton txtGenerateQR;
    public static javax.swing.JLabel txtName;
    private javax.swing.JTextArea txtReadContent;
    // End of variables declaration//GEN-END:variables
}
