/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qrcode;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.dbHelper.DBHandler;

/**
 *
 * @author Thomas
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    DBHandler handler;
    String fname;
    String lname;

    public Register() {

        initComponents();
        setLocationRelativeTo(null);
        txtError.setVisible(false);
        txtError1.setVisible(false);
        error.setVisible(false);
//        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signupNav = new javax.swing.JButton();
        loginNav = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        layeredPane = new javax.swing.JLayeredPane();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnReset = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        txtError1 = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSignupFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSignupLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSignupEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSignupNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSignupReset = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSignupPassword = new javax.swing.JPasswordField();
        txtSignupCPassword = new javax.swing.JPasswordField();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupNav.setBackground(new java.awt.Color(0, 102, 102));
        signupNav.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupNav.setForeground(new java.awt.Color(255, 255, 255));
        signupNav.setText("SIGN UP");
        signupNav.setBorder(null);
        signupNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupNavActionPerformed(evt);
            }
        });
        jPanel1.add(signupNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 90, 34));

        loginNav.setBackground(new java.awt.Color(0, 102, 102));
        loginNav.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        loginNav.setForeground(new java.awt.Color(255, 255, 255));
        loginNav.setText("LOGIN");
        loginNav.setBorder(null);
        loginNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNavActionPerformed(evt);
            }
        });
        jPanel1.add(loginNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 90, 34));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QR CODE GENERATOR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("(QUICK RESPONSE CODE)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 83));

        layeredPane.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(5, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL");

        txtEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setToolTipText("USERNAME");
        txtEmail.setBorder(null);

        txtPassword.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("PASSWORD");
        txtPassword.setBorder(null);

        btnReset.setBackground(new java.awt.Color(5, 0, 0));
        btnReset.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(5, 0, 0));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 51, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("*");

        txtError1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtError1.setForeground(new java.awt.Color(255, 51, 0));
        txtError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError1.setText("*");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(69, 69, 69)
                        .addComponent(btnLogin))
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(4, 4, 4)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtError)
                    .addComponent(txtError1))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(txtError))
                        .addGap(40, 40, 40)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtError1))
                .addGap(71, 71, 71)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layeredPane.add(loginPanel, "card2");

        signupPanel.setBackground(new java.awt.Color(5, 0, 0));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SIGN UP");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("First Name");

        txtSignupFname.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtSignupFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupFname.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Last Name");

        txtSignupLname.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtSignupLname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupLname.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");

        txtSignupEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtSignupEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupEmail.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Number");

        txtSignupNumber.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtSignupNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupNumber.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password");

        btnSignupReset.setBackground(new java.awt.Color(5, 0, 0));
        btnSignupReset.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSignupReset.setForeground(new java.awt.Color(255, 255, 255));
        btnSignupReset.setText("RESET");
        btnSignupReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSignupReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupResetActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(5, 0, 0));
        btnSignup.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("SIGN UP");
        btnSignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Confirm Password");

        txtSignupPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSignupPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupPassword.setBorder(null);

        txtSignupCPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSignupCPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSignupCPassword.setBorder(null);

        error.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setText("*");

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                        .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSignupFname, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSignupLname, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSignupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSignupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(signupPanelLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(signupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtSignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signupPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(signupPanelLayout.createSequentialGroup()
                                                .addComponent(btnSignupReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(75, 75, 75)
                                                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSignupCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSignupFname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSignupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSignupLname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtSignupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSignupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSignupCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignupReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        layeredPane.add(signupPanel, "card3");

        getContentPane().add(layeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        handler = new DBHandler();
        ResultSet rs = null;

        String email = txtEmail.getText();
        String pass = txtPassword.getText();
        int counter = 0;

        if (!email.equals("") && !pass.equals("")) {
            txtError.setVisible(false);
            txtError1.setVisible(false);
            String select = "SELECT * FROM users WHERE Email = ? AND Password = ?";

            try {
                PreparedStatement pst = handler.getdbConnection().prepareStatement(select);
                pst.setString(1, email);
                pst.setString(2, pass);
                rs = pst.executeQuery();

                if (rs.next()) {
                    counter++;
                    email = rs.getString("Email");
                    pass = rs.getString("Password");
                    fname = rs.getString("FirstName");
                    lname = rs.getString("LastName");

                }
                if (counter == 1) {
                    txtEmail.setText(email);
                    txtPassword.setText(pass);
                    new Generator().show();
                    Generator.txtName.setText(fname + " " + lname);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Welcome " + fname);
                } else {
                    JOptionPane.showMessageDialog(this, "Either your username and/or password is incorrect");
                }

            } catch (SQLException e) {
                System.out.println(e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Field can't be empty!");
            txtError.setVisible(true);
            txtError1.setVisible(true);

            if (!email.isEmpty()) {
                txtError.setVisible(false);
            } else if (!pass.isEmpty()) {
                txtError1.setVisible(false);
            } else {

                txtError.setVisible(true);
                txtError1.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtEmail.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void loginNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNavActionPerformed
        // TODO add your handling code here:
        changePanel(loginPanel);
    }//GEN-LAST:event_loginNavActionPerformed

    private void signupNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupNavActionPerformed
        // TODO add your handling code here:
        changePanel(signupPanel);
    }//GEN-LAST:event_signupNavActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:

        handler = new DBHandler();

        try {
            String insert = "INSERT INTO users VALUES(?,?,?,?,?)";
            PreparedStatement pst1 = handler.getdbConnection().prepareStatement(insert);

            pst1.setString(1, txtSignupFname.getText());
            pst1.setString(2, txtSignupLname.getText());
            pst1.setString(3, txtSignupEmail.getText());
            pst1.setString(4, txtSignupNumber.getText());
            pst1.setString(5, txtSignupPassword.getText());

            pst1.executeUpdate();
            System.out.println("INSERTED!");
        } catch (SQLException e) {
            System.out.println("ERROR OCCURRED ==>>> " + e.toString());
        }
        txtSignupCPassword.setText("");
        txtSignupEmail.setText("");
        txtSignupFname.setText("");
        txtSignupLname.setText("");
        txtSignupNumber.setText("");
        txtSignupPassword.setText("");

    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnSignupResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupResetActionPerformed
        // TODO add your handling code here:

        txtSignupCPassword.setText("");
        txtSignupEmail.setText("");
        txtSignupFname.setText("");
        txtSignupLname.setText("");
        txtSignupNumber.setText("");
        txtSignupPassword.setText("");

    }//GEN-LAST:event_btnSignupResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    public void changePanel(JPanel panel) {

        layeredPane.removeAll();
        layeredPane.add(panel);
        layeredPane.repaint();
        layeredPane.revalidate();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton btnSignupReset;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JButton loginNav;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton signupNav;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtError;
    private javax.swing.JLabel txtError1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtSignupCPassword;
    public static javax.swing.JTextField txtSignupEmail;
    public static javax.swing.JTextField txtSignupFname;
    public static javax.swing.JTextField txtSignupLname;
    public static javax.swing.JTextField txtSignupNumber;
    public static javax.swing.JPasswordField txtSignupPassword;
    // End of variables declaration//GEN-END:variables
}
